[package]
name = "art-olc"
version = "0.1.0"
authors = ["Yilin Chen <sticnarf@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-epoch = "0.8.2"
static_assertions = "1.1.0"

[dev-dependencies]
rand = "0.7.3"
rand_distr = "0.2.2"